#! /bin/bash

function create_debian {
    mkdir src
    cd src
    mkdir DEBIAN
    mkdir -p usr/bin
    cp $path usr/bin/
    cp $file DEBIAN/
    cd ..
    hash dpkg 2> /dev/null || sudo apt-get -y install dpkg
    dpkg-deb --build src
    packagename=$( grep "Package" "$file" | cut -d' ' -f2 )
    packageversion=$( grep "Version" "$file" | cut -d' ' -f2 )
    packagearchitecture=$( grep "Architecture" "$filename" | cut -d' ' -f2 )
    out=$(echo "$packagename"_"$packageversion"_"$packagearchitecture")
    mv src.deb $out.deb
    rm -rf src
    hash s3cmd 2> /dev/null || sudo apt-get -y install s3cmd
    s3cmd -P put $dir/$out.deb $url/$context/
}


#main
while getopts "p:f:u:hc:" opt; do
    case $opt in
        p)
            path=$OPTARG
            ;;
        f)
            file=$OPTARG
            ;;
        u)
            url=$OPTARG
            ;;
        h)
            echo "Usage: <command name> <option1> <argument 1> <option2> <argument 2>"
            echo "Options :"
            echo "  -p    : path to the debian package or path to the source directory"
            echo "  -u    : url to the repository"
            echo "  -c    : where under the repository you want to place the package "
            echo "        : you can choose from stable | unstable | testing"
            exit 0
            ;;
        c)
            context=$OPTARG
            if [ "$context" != "stable" ] && [ "$context" != "unstable" ] && [ "$context" != "testing" ]; then
                echo "ERROR: Invalid context"
                exit 1
            fi
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument"
            exit 1
            ;;
        esac
done


filename=$( echo ${path##*/} )
extension=${filename##*.}

if [ "$extension" = 'deb' ]; then
    hash s3cmd 2> /dev/null || sudo apt-get -y install s3cmd
    s3cmd -P put $path $url/$context
elif [ -f "$path" ]; then
    create_debian
else
    echo "ERROR: Given path is not a file nor a debian file"
fi
