#! /bin/bash

while getopts "u:n:h" opt; do
    case $opt in
        u)
            url=$OPTARG
            ;;
        h)
            echo "Usage: <command name> <option1> <argument 1>"
            echo "Options :"
            echo "  -u    : path where the repository is present"
            exit 0
            ;;
        n)
            packagename=$OPTARG
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument"
            exit 1
            ;;
        esac
done


path=${url%/*}

dir=${path##*/}

temp=${path%/*}

sudo sh -c "echo 'deb $temp/ $dir/'  >> /etc/apt/sources.list"
sudo apt-get update
sudo apt-get install $packagename
