#! /bin/bash

function create_debian {
    dir=$( echo ${path%/*} )
    cd $dir
    dpkg-deb --build $filename
    s3cmd -P put $dir/$filename.deb $url/$context/
}


#main
#! /bin/bash

while getopts "p:u:hc:" opt; do
    case $opt in
        p)
            path=$OPTARG
            ;;
        u)
            url=$OPTARG
            ;;
        h)
            echo "Usage: <command name> <option1> <argument 1> <option2> <argument 2>"
            echo "Options :"
            echo "  -p    : path to the debian package or path to the source directory"
            echo "  -u    : url to the repository"
            echo "  -c    : where under the repository you want to place the package "
            echo "        : you can choose from stable | unstable | testing"
            exit 0
            ;;
        c)
            context=$OPTARG
            if [ "$context" != "stable" ] && [ "$context" != "unstable" ] && [ "$context" != "testing" ]; then
                echo "ERROR: Invalid context"
                exit 1
            fi
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument"
            exit 1
            ;;
        esac
done


filename=$( echo ${path##*/} )
extension=${filename##*.}

if [ "$extension" = 'deb' ]; then
    #cd /home/jayanth/Desktop/
    #line=$(head -n 1 link.txt)
    s3cmd -P put $path $url/$context
elif [ -d "$path" ]; then
    create_debian
else
    echo "Given path is not a directory nor a debian file"
fi
