#! /bin/bash

while getopts "p:u:hc:" opt; do
    case $opt in
        p)
            path=$OPTARG
            ;;
        u)
            url=$OPTARG
            ;;
        h)
            echo "Usage: <command name> <option1> <argument 1> <option2> <argument 2>"
            echo "Options :"
            echo "  -p    : path to the source"
            echo "  -u    : url to the repository"
            echo "  -c    : where under the repository you want to place the package "
            echo "        : you can choose from stable | unstable | testing"
            exit 0
            ;;
        c)
            context=$OPTARG
            if [ "$context" != "stable" ] && [ "$context" != "unstable" ] && [ "$context" != "testing" ]; then
                echo "Invalid context"
                exit 1
            fi
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument"
            exit 1
            ;;
        esac
done

tar xvzf $path

## suppose the path is /home/jayanth/Desktop/nginx-1.6.2.tar.gz
#  then topath = /home/jayanth/Desktop/nginx-1.6.2.tar

topath=$( echo ${path%.*} )


## then finaltopath = /home/jayanth/Desktop/nginx-1.6.2

finaltopath=$( echo ${topath%.*} )


## then filename = nginx-1.6.2

filename=$( echo ${finaltopath##*/})


## then packagename = nginx

packagename=$( echo ${filename%-*})


cd $finaltopath
./configure
make
echo -ne '\n' | sudo checkinstall -D --install=no
file=$( ls | grep "deb" )
#confgfile=$(head -n 1 /home/jayanth/Desktop/link.txt)
s3cmd -P put ./$file $url/$context/
