#! /bin/bash

while getopts "u:h" opt; do
    case $opt in
        u)
            url=$OPTARG
            ;;
        h)
            echo "Usage: <command name> <option1> <argument 1>"
            echo "Options :"
            echo "  -u    : path where the repository is present"
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument"
            exit 1
            ;;
        esac
done

## suppose path is s3://repository.kenalyse.io/my-repository/stable/helloe_1.1-1_all.deb

## then path = s3://repository.kenalyse.io/my-repository/stable

path=${url%/*}
#echo $path

##then dir = stable

dir=${path##*/}
#echo $dir

##then temp = s3://repository.kenalyse.io/my-repository

temp=${path%/*}
#echo $temp

packagename=$2
sudo sh -c "echo 'deb $temp/ $dir/'  >> /etc/apt/sources.list"
sudo apt-get update
sudo apt-get install $packagename

